# Generated by Django 5.2.8 on 2025-12-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='avg_time_per_question',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='difficulty_progression',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='final_difficulty',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='difficulty',
            field=models.FloatField(default=1.0),
        ),
    ]
