# Generated by Django 5.2.8 on 2025-12-07 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_practicesession_avg_time_per_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='accuracy_per_question',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='common_errors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='concept_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='time_per_question',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='score',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='practicesession',
            name='topics',
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.FloatField(default=1.0)),
                ('prerequisites', models.ManyToManyField(blank=True, to='student.concept')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=50)),
                ('question_data', models.JSONField()),
                ('student_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.FloatField()),
                ('difficulty', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.concept')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='student.practicesession')),
            ],
        ),
        migrations.AddField(
            model_name='practicesession',
            name='topics',
            field=models.ManyToManyField(related_name='practice_sessions', to='student.concept'),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.FloatField(default=0.0)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Progresses',
                'unique_together': {('student', 'concept')},
            },
        ),
    ]
