# Generated by Django 5.2.8 on 2025-12-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_practicesession_accuracy_per_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='practice_mode',
            field=models.CharField(default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='timer_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
