# Generated by Django 5.2.8 on 2025-12-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_practicesession_practice_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='skipped_questions',
            field=models.IntegerField(default=0),
        ),
    ]
