# Generated by Django 5.2.8 on 2025-12-06 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_section_section_teacher'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='group_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.group'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teacher.class'),
        ),
    ]
