# Generated by Django 5.2.8 on 2025-12-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_section_teacher'),
        ('teacher', '0002_assignment_group_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='class_assigned',
        ),
        migrations.AddField(
            model_name='assignment',
            name='section_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.section'),
        ),
    ]
