# Generated by Django 5.2.8 on 2025-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academicclass_class_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
